#!/usr/bin/env bash

remove_project_dir=$1

separator() { printf %$1s | tr " " "-" && echo ""; }

echo_message() { separator $2 && echo -e $1 && separator $2; }

cd ../

if [[ ${remove_project_dir} == "" ]]; then
	echo_message "You did not specify project dir for removing." 45
	exit 1
else
	if [[ -d ${remove_project_dir} ]]; then

		if [[ -e ${remove_project_dir}/.python-version ]]; then

			read -r env < ${remove_project_dir}/.python-version

			echo_message "Uninstall virtualenv '"${env}"'?\nPress 'Enter' \
				or 'y' to delete or any key to exit." 50

			read -s -n 1 delete_env

			if [[ ${delete_env} == "" || ${delete_env} == "y" ]]; then
				pyenv uninstall ${env}
				echo "Virtualenv '"${env}"' uninstalled."
			fi
		fi

		rm -rf ${remove_project_dir}
		echo_message "Project removed." 20

	else
		echo_message "Directory '"${remove_project_dir}"' does not exist." 50
		exit 1
	fi
fi
