#!/usr/bin/env bash

project_to_remove=$1
env=""

separator() { printf %$1s | tr " " "-" && echo ""; }

echo_message() { separator $2 && echo -e $1 && separator $2; }

if [[ ${project_to_remove} == "" ]]; then
	echo_message "You did not specify project dir for removing." 45
	exit 1
else
	if [[ -d ${project_to_remove} ]]; then

		if [[ -e ${project_to_remove}/.python-version ]]; then
			read -r env < ${project_to_remove}/.python-version
		fi

		rm -rf ${project_to_remove}
		echo_message "Project removed." 20
	else
		echo_message "Directory '"${project_to_remove}"' does not exist." 50
		exit 1
	fi
fi

if [[ ${env} != "" ]]; then
	pyenv uninstall ${env}
fi
